### ISSUE TITLE
column ordering

### ISSUE THREAD

**Issue by kieranjmartin** [gowerc/diffdf#28] opened 2019-03-25 10:54 UTC
One of the big differences between all.equal and diffdf is that if columns are in different orders between data frames, diffdf ignores it and all.equal errors (and usually in a way thats very hard to debug :) ). 

I think this is a good behaviour, but I can imagine contexts where you may want to care about column ordering. I'm not sure how easy it would be to integrate this. I guess I'd have another check called column match, and if the names dont match in the same position, just don't compare them any further (as we do with failed class matches) and return a tibble listing order matching failures.

**Comment by gowerc** [comment] 2019-03-25 14:38
This is quite a neat idea, I don't think I would stop processing/comparing though if the columns aren't in order.  I think it would be best to treat it as its own independent test category

Are columns in A  in B   - Pass
Are values of A = values in B - Pass
Are columns of A in the same order of columns in B - Fail 

I would then add an option to enable / disable this test with it set to off by default. 

`diffdf_options( column_order_important = FALSE ) `

**Comment by kieranjmartin** [comment] 2020-02-04 13:46
Yes that makes sense to me

**Comment by gowerc** [comment] 2020-04-09 13:23
Duplicate of #32

**Closed by gowerc** 2020-04-09 13:23 UTC
Labels: Effort: Medium, Priority: Medium, enhancement
