### ISSUE TITLE
Problems with the development version of tibble

### ISSUE THREAD

**Issue by krlmlr** [gowerc/diffdf#16] opened 2018-12-20 14:50 UTC
I'm in the process of preparing the release for _tibble_ 2.0.0. The _diffdf_ package imports _tibble_.

I'm seeing errors when testing your package with the dev version of _tibble_. Unfortunately I can't relate the errors I see to changes we've made to _tibble_. Also, a first pass of checking all downstream dependencies did not catch this problem.

Could you please install the development version of _tibble_ and run the tests in your package, so that we get a better understanding for the reason of the new test failures?

See https://www.tidyverse.org/articles/2018/11/tibble-2.0.0-pre-announce/ for details on the upcoming release.

**Comment by kieranjmartin** [comment] 2018-12-20 15:10
Without looking, I'd guess that this is triggered by the print method tests, which compare the output with canonical files. As we make use of tibble print for at least some of our output, any changes in that will cause our tests to fail.

I am unlikely to get to this until the new year, don't know about you @gowerc

**Comment by gowerc** [comment] 2018-12-21 09:46
Hi @krlmlr ,

Can I just double check that you meant to post this on our repo as you have mentioned the `postal` package in your message for which this is not the repo for :) 

I will check the new version of tibble anyway (as we do import it) to make sure our package works with it.

@kieranjmartin  I am not sure that it is the print method as we previously removed our reliance on the tibble print method in favour of creating our own ascii print function which can be seen in the `ascii_tables.R` file

**Comment by krlmlr** [comment] 2018-12-21 15:11
Thanks. Yes, this was a typo. To me it does look like numbers are off, in addition to the printed output. I appreciate your input!

**Comment by gowerc** [comment] 2019-01-02 12:10
Hi @krlmlr ,

Apologies for the delay both of us have been away during the holiday period.  This issue was being caused by us relying on the functionality that when you use as.tibble on a named vector that it still stores the names information which could then be extracted via rownames_to_column. 

Essentially we were doing this:
```
rownames_to_column(as.tibble( c(a=1, b=2)))
```

(Just an FYI as I'm not sure if you intended or not for this functionality to be removed)

Regardless I've updated our code to be more explicit about getting the rownames,  Hopefully we should have the updated version submitted to CRAN early next week (just waiting on @kieranjmartin  to come back from holiday).

**Comment by kieranjmartin** [comment] 2019-01-09 07:00
The pr is now merged, this just now needs to be submitted to cran

**Closed** 2019-01-09 09:59 UTC
Labels: bug
